name: Release

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Cache dependencies
        id: cache-dependencies
        uses: actions/cache@v2
        with:
          path: dependencies
          key: release-dependencies-20210530

      - name: Install dependencies
        run: sudo bash script/build.sh

      - name: Set environment variable
        run: echo "RELEASE_VERSION=${TAG_NAME:1}" >> $GITHUB_ENV
        env:
          TAG_NAME: ${{ github.event.release.tag_name }}

      - name: Configure
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build --config Release -j"$(nproc)"

      - name: CPack
        run: |
          cd build
          cpack
          mv kcc-${{ env.RELEASE_VERSION }}-Linux.deb \
          kcc-${{ env.RELEASE_VERSION }}-ubuntu-20.04.deb
          mv kcc-${{ env.RELEASE_VERSION }}-Linux.tar.gz \
          kcc-${{ env.RELEASE_VERSION }}-ubuntu-20.04.tar.gz

      - name: Install
        run: sudo dpkg -i build/kcc-${{ env.RELEASE_VERSION }}-ubuntu-20.04.deb

      - name: Run executable
        run: kcc -v

      # https://github.com/softprops/action-gh-release
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/kcc-${{ env.RELEASE_VERSION }}-ubuntu-20.04.deb
            build/kcc-${{ env.RELEASE_VERSION }}-ubuntu-20.04.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
